-- Add missing performance columns to flow_message_metrics for Flow Series data
-- Run this in Supabase SQL Editor

ALTER TABLE flow_message_metrics 
ADD COLUMN IF NOT EXISTS week_date DATE,
ADD COLUMN IF NOT EXISTS opens INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS opens_unique INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS clicks INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS clicks_unique INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS conversions INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS conversion_value NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS delivery_rate NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS bounce_rate NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS recipients INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS revenue_per_recipient NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS average_order_value NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS delivered INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS bounced INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS unsubscribes INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS spam_complaints INTEGER DEFAULT 0,

-- Add message content columns from Get Flow Message API
ADD COLUMN IF NOT EXISTS channel VARCHAR(50),
ADD COLUMN IF NOT EXISTS preview_text TEXT,
ADD COLUMN IF NOT EXISTS from_email VARCHAR(255),
ADD COLUMN IF NOT EXISTS from_label VARCHAR(255),
ADD COLUMN IF NOT EXISTS reply_to_email VARCHAR(255),
ADD COLUMN IF NOT EXISTS cc_email VARCHAR(255),
ADD COLUMN IF NOT EXISTS bcc_email VARCHAR(255),
ADD COLUMN IF NOT EXISTS message_created TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS message_updated TIMESTAMP WITH TIME ZONE; 